### ISSUE TITLE
Module has no exported member 'MdInputContainer'

### ISSUE THREAD

**Issue by GavinSong123** [michael-mcanulty/md-datetimepicker#5]
I import MdDatetimepickerModule and other dependency in my project then run the code. It has error:
```
ERROR in node_modules/md-datetimepicker/datetimepicker-input.d.ts (11,10): Module '"node_modules/@angular/material/material"' has no exported member 'MdInputContainer'.
```
I'm using material2 in my project.

**Comment by Iraecio** [comment]
This is beakchange of material

and move all communication with mdInput into a well defined interface. This is a pre-requisite to making md-select share a container element with mdInput.

This is a first-pass PR that tries to avoid breaking changes as much as possible. We can update Google's codebase and remove the old selectors and class names in the future.

@tinayuangao This should also allow you to integrate md-chip-list with the input more easily.

Incremental step toward #2124

BREAKING CHANGE: MdInputContainer is now MdFormField and MdInputDirective is now MdInput

**Comment by GavinSong123** [comment]
got it, thx
